<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <ApplicationIcon>redicon.ico</ApplicationIcon>
    <Version>0.1.25</Version>
    <AssemblyVersion>0.1.25.0</AssemblyVersion>
    <FileVersion>0.1.25.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.14" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.14" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.14" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="redicon.png" />
    <None Include="redicon.png" CopyToOutputDirectory="PreserveNewest" />
    <None Include="redicon.ico" />
  </ItemGroup>
</Project>
